SYS.ELB:
  lbaas_instance_id:
    - m1_cps
    - m2_act_conn
    - m3_inact_conn
    - m4_ncps
    - m5_in_pps
    - m6_out_pps
    - m7_in_Bps
    - m8_out_Bps
    - m9_abnormal_servers
    - ma_normal_servers
    - mb_l7_qps
    - mc_l7_http_2xx
    - md_l7_http_3xx
    - me_l7_http_4xx
    - mf_l7_http_5xx
    - m10_l7_http_other_status
    - m11_l7_http_404
    - m12_l7_http_499
    - m13_l7_http_502
    - m14_l7_rt
    - m15_l7_upstream_4xx
    - m16_l7_upstream_5xx
    - m17_l7_upstream_rt
    - m1a_l7_upstream_rt_max
    - m1b_l7_upstream_rt_min
    - m1c_l7_rt_max
    - m1d_l7_rt_min
    - m17_l7_upstream_rt_p90
    - m17_l7_upstream_rt_p95
    - m17_l7_upstream_rt_p99
    - m1e_server_rps
    - m21_client_rps
    - m1f_lvs_rps
    - m22_in_bandwidth
    - m23_out_bandwidth
    - l4_ncps_usage
    - l4_con_usage
    - l4_in_bps_usage
    - l4_out_bps_usage
    - l7_ncps_usage
    - l7_con_usage
    - l7_in_bps_usage
    - l7_out_bps_usage
    - l7_qps_usage
  'lbaas_instance_id,lbaas_listener_id':
    - m1_cps
    - m2_act_conn
    - m4_ncps
    - m3_inact_conn
    - m7_in_Bps
    - m8_out_Bps
    - m5_in_pps
    - m6_out_pps
    - mb_l7_qps
    - mc_l7_http_2xx
    - md_l7_http_3xx
    - me_l7_http_4xx
    - mf_l7_http_5xx
    - m10_l7_http_other_status
    - m11_l7_http_404
    - m12_l7_http_499
    - m13_l7_http_502
    - m14_l7_rt
    - m15_l7_upstream_4xx
    - m16_l7_upstream_5xx
    - m17_l7_upstream_rt
    - m1a_l7_upstream_rt_max
    - m1b_l7_upstream_rt_min
    - m1c_l7_rt_max
    - m1d_l7_rt_min
    - m17_l7_upstream_rt_p90
    - m17_l7_upstream_rt_p95
    - m17_l7_upstream_rt_p99
    - m1e_server_rps
    - m21_client_rps
    - m1f_lvs_rps
    - m22_in_bandwidth
    - m23_out_bandwidth
  'lbaas_instance_id,lbaas_pool_id':
    - m9_abnormal_servers
    - ma_normal_servers
    - m17_l7_upstream_rt
    - mb_l7_qps
    - m16_l7_upstream_5xx
    - m15_l7_upstream_4xx
    - m19_l7_upstream_3xx
    - m18_l7_upstream_2xx
    - m1a_l7_upstream_rt_max
    - m1b_l7_upstream_rt_min
    - m17_l7_upstream_rt_p90
    - m17_l7_upstream_rt_p95
    - m17_l7_upstream_rt_p99
    - m24_l7_req_Bps
    - m25_l7_resp_Bps
SYS.RDS:
  rds_cluster_id:
    - rds001_cpu_util
    - rds002_mem_util
    - rds003_iops
    - rds004_bytes_in
    - rds005_bytes_out
    - rds006_conn_count
    - rds007_conn_active_count
    - rds008_qps
    - rds009_tps
    - rds010_innodb_buf_usage
    - rds011_innodb_buf_hit
    - rds012_innodb_buf_dirty
    - rds013_innodb_reads
    - rds014_innodb_writes
    - rds015_innodb_read_count
    - rds016_innodb_write_count
    - rds017_innodb_log_write_req_count
    - rds018_innodb_log_write_count
    - rds019_innodb_log_fsync_count
    - rds020_temp_tbl_count
    - rds021_myisam_buf_usage
    - rds022_myisam_buf_write_hit
    - rds023_myisam_buf_read_hit
    - rds024_myisam_disk_write_count
    - rds025_myisam_disk_read_count
    - rds026_myisam_buf_write_count
    - rds027_myisam_buf_read_count
    - rds028_comdml_del_count
    - rds029_comdml_ins_count
    - rds030_comdml_ins_sel_count
    - rds031_comdml_rep_count
    - rds032_comdml_rep_sel_count
    - rds033_comdml_sel_count
    - rds034_comdml_upd_count
    - rds035_innodb_del_row_count
    - rds036_innodb_ins_row_count
    - rds037_innodb_read_row_count
    - rds038_innodb_upd_row_count
    - rds039_disk_usage
    - rds039_disk_util
    - rds047_disk_total_size
    - rds048_disk_used_size
    - rds049_disk_read_throughput
    - rds050_disk_write_throughput
    - rds051_avg_disk_sec_per_read
    - rds052_avg_disk_sec_per_write
    - rds053_avg_disk_queue_length
    - rds072_conn_usage
    - rds073_replication_delay
    - rds074_slow_queries
    - rds075_avg_disk_ms_per_read
    - rds076_avg_disk_ms_per_write
    - rds020_temp_tbl_rate
    - sys_swap_usage
    - rds_innodb_lock_waits
    - rds_bytes_recv_rate
    - rds_bytes_sent_rate
    - rds_innodb_pages_read_rate
    - rds_innodb_pages_written_rate
    - rds_innodb_os_log_written_rate
    - rds_innodb_buffer_pool_read_requests_rate
    - rds_innodb_buffer_pool_write_requests_rate
    - rds_innodb_buffer_pool_pages_flushed_rate
    - rds_innodb_log_waits_rate
    - rds_created_tmp_tables_rate
    - rds_wait_thread_count
    - rds_innodb_row_lock_time_avg
    - rds_innodb_row_lock_current_waits
    - rds077_vma
    - rds078_threads
    - rds079_vm_hwm
    - rds080_vm_peak
    - rds081_vm_ioutils
    - rds082_semi_sync_tx_avg_wait_time
    - rds173_replication_delay_avg
    - rds_innodb_log_waits_count
    - rds_buffer_pool_wait_free
    - rds_conn_active_usage
    - rds_long_transaction
    - rds_mdl_lock_count
  postgresql_cluster_id:
    - rds001_cpu_util
    - rds002_mem_util
    - rds003_iops
    - rds004_bytes_in
    - rds005_bytes_out
    - rds039_disk_usage
    - rds039_disk_util
    - rds040_transaction_logs_usage
    - rds041_replication_slot_usage
    - rds042_database_connections
    - rds043_maximum_used_transaction_ids
    - rds044_transaction_logs_generations
    - rds045_oldest_replication_slot_lag
    - rds046_replication_lag
    - rds047_disk_total_size
    - rds048_disk_used_size
    - rds049_disk_read_throughput
    - rds050_disk_write_throughput
    - rds051_avg_disk_sec_per_read
    - rds052_avg_disk_sec_per_write
    - rds053_avg_disk_queue_length
    - rds081_qps
    - rds082_tps
    - rds083_conn_usage
  rds_cluster_sqlserver_id:
    - rds001_cpu_util
    - rds002_mem_util
    - rds003_iops
    - rds004_bytes_in
    - rds005_bytes_out
    - rds039_disk_usage
    - rds039_disk_util
    - rds047_disk_total_size
    - rds048_disk_used_size
    - rds049_disk_read_throughput
    - rds050_disk_write_throughput
    - rds051_avg_disk_sec_per_read
    - rds052_avg_disk_sec_per_write
    - rds053_avg_disk_queue_length
    - rds054_db_connections_in_use
    - rds055_transactions_per_sec
    - rds056_batch_per_sec
    - rds057_logins_per_sec
    - rds058_logouts_per_sec
    - rds059_cache_hit_ratio
    - rds060_sql_compilations_per_sec
    - rds061_sql_recompilations_per_sec
    - rds062_full_scans_per_sec
    - rds063_errors_per_sec
    - rds064_latch_waits_per_sec
    - rds065_lock_waits_per_sec
    - rds066_lock_requests_per_sec
    - rds067_timeouts_per_sec
    - rds068_avg_lock_wait_time
    - rds069_deadlocks_per_sec
    - rds070_checkpoint_pages_per_sec
    - rds077_replication_delay
    - mssql_mem_grant_pending
    - mssql_lazy_write_per_sec
    - mssql_page_life_expectancy
    - mssql_page_reads_per_sec
SYS.DCS:
  dcs_instance_id:
    - cpu_usage
    - memory_usage
    - net_in_throughput
    - net_out_throughput
    - connected_clients
    - client_longest_out_list
    - client_biggest_in_buf
    - blocked_clients
    - used_memory
    - used_memory_rss
    - used_memory_peak
    - used_memory_lua
    - memory_frag_ratio
    - total_connections_received
    - total_commands_processed
    - instantaneous_ops
    - total_net_input_bytes
    - total_net_output_bytes
    - instantaneous_input_kbps
    - instantaneous_output_kbps
    - rejected_connections
    - sync_full
    - sync_partial_ok
    - sync_partial_err
    - keys
    - expired_keys
    - evicted_keys
    - expires
    - keyspace_hits
    - keyspace_misses
    - set
    - pubsub_channels
    - pubsub_patterns
    - aof_current_size
    - latest_fork_usec
    - keyspace_hits_perc
    - used_memory_dataset
    - used_memory_dataset_perc
    - get
    - del
    - mset
    - mget
    - expire
    - hset
    - hget
    - hmset
    - hmget
    - hdel
    - auth_errors
    - command_max_delay
    - is_slow_log_exist
    - slave_psyncing_opid_gap_max
    - slave_state_abnormal_count
    - sadd
    - smembers
    - rx_controlled
    - bandwidth_usage
    - disk_device_io_util_max
    - disk_device_io_util_avg
    - disk_util_inband
    - disk_device_read_requests_rate_max
    - disk_device_read_requests_rate_avg
    - disk_device_write_requests_rate_max
    - disk_device_write_requests_rate_avg
    - node_status
  dcs_memcached_instance_id:
    - cpu_usage
    - memory_usage
    - net_in_throughput
    - net_out_throughput
    - mc_connected_clients
    - mc_used_memory
    - mc_used_memory_rss
    - mc_used_memory_peak
    - mc_memory_frag_ratio
    - mc_connections_received
    - mc_commands_processed
    - mc_instantaneous_ops
    - mc_net_input_bytes
    - mc_net_output_bytes
    - mc_instantaneous_input_kbps
    - mc_instantaneous_output_kbps
    - mc_rejected_connections
    - mc_sync_full
    - mc_sync_partial_ok
    - mc_sync_partial_err
    - mc_expired_keys
    - mc_evicted_keys
    - mc_aof_current_size
    - mc_cmd_get
    - mc_cmd_set
    - mc_cmd_flush
    - mc_cmd_touch
    - mc_get_hits
    - mc_get_misses
    - mc_delete_hits
    - mc_delete_misses
    - mc_incr_hits
    - mc_incr_misses
    - mc_decr_hits
    - mc_decr_misses
    - mc_cas_hits
    - mc_cas_misses
    - mc_cas_badval
    - mc_touch_hits
    - mc_touch_misses
    - mc_auth_cmds
    - mc_auth_errors
    - mc_curr_items
    - mc_command_max_delay
    - mc_keyspace_hits_perc
    - mc_is_slow_log_exist
    - disk_device_io_util_max
    - disk_device_io_util_avg
    - disk_util_inband
    - disk_device_read_requests_rate_max
    - disk_device_read_requests_rate_avg
    - disk_device_write_requests_rate_max
    - disk_device_write_requests_rate_avg
SYS.NAT:
  nat_gateway_id:
    - snat_connection
    - inbound_bandwidth
    - outbound_bandwidth
    - inbound_pps
    - outbound_pps
    - inbound_traffic
    - outbound_traffic
    - snat_connection_ratio
    - inbound_bandwidth_ratio
    - outbound_bandwidth_ratio
